name: 'x_ads_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars: 
  x_ads_schema: x_ads_integration_tests_1
  x_ads_account_history_identifier: "x_ads_account_history_data"
  x_ads_account_hourly_report_identifier: "x_ads_account_performance_hourly_report_data"
  x_ads_ad_group_history_identifier: "x_ads_ad_group_history_data"
  x_ads_ad_group_hourly_report_identifier: "x_ads_ad_group_performance_hourly_report_data"
  x_ads_ad_history_identifier: "x_ads_ad_history_data"
  x_ads_ad_hourly_report_identifier: "x_ads_ad_performance_hourly_report_data"
  x_ads_campaign_history_identifier: "x_ads_campaign_history_data"
  x_ads_campaign_hourly_report_identifier: "x_ads_campaign_performance_hourly_report_data"
  x_ads_keyword_history_identifier: "x_ads_keyword_history_data"
  x_ads_keyword_hourly_report_identifier: "x_ads_keyword_performance_hourly_report_data"
  x_ads_creative_history_identifier: "x_ads_creative_history_data"
  x_ads_creative_url_tag_history_identifier: "x_ads_creative_url_tag_history_data"
  x_ads_search_term_report_identifier: "x_ads_search_term_report_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']